-- ЛИНИЯ / Supabase database setup
-- 1) Run this whole file in Supabase SQL Editor.
-- 2) Create YOUR account in the site.
-- 3) At the bottom, run the one-time OWNER bootstrap query with your email.
-- The owner is stored by UUID, so changing email later does not change ownership.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-zA-Z0-9_]{3,24}$'),
  display_name text not null default '',
  avatar_url text,
  bio text not null default '',
  is_banned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint different_users check (user_a <> user_b),
  constraint ordered_users check (user_a < user_b),
  unique(user_a,user_b)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 4000),
  message_type text not null default 'text' check (message_type in ('text','voice')),
  media_url text,
  duration integer,
  created_at timestamptz not null default now(),
  edited_at timestamptz
);

create table if not exists public.app_owner (
  singleton boolean primary key default true check (singleton = true),
  owner_user_id uuid not null unique references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_idx on public.messages(conversation_id,created_at);
create index if not exists profiles_username_idx on public.profiles(lower(username));

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.app_owner enable row level security;

-- Owner check. Users cannot edit this table from the browser.
create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.app_owner where owner_user_id = auth.uid());
$$;

revoke all on public.app_owner from anon, authenticated;
grant select on public.app_owner to authenticated;

drop policy if exists app_owner_read on public.app_owner;
create policy app_owner_read on public.app_owner for select to authenticated using (true);

create or replace function public.is_banned_user(uid uuid)
returns boolean
language sql stable security definer set search_path=public
as $$ select coalesce((select is_banned from public.profiles where id=uid), false); $$;

revoke all on function public.is_banned_user(uuid) from public;
grant execute on function public.is_banned_user(uuid) to authenticated;

-- Profiles
 drop policy if exists profiles_read_auth on public.profiles;
create policy profiles_read_auth on public.profiles
for select to authenticated
using (not is_banned or id = auth.uid() or public.is_owner());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
for insert to authenticated
with check (id=auth.uid() and not public.is_owner());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated
using ((id=auth.uid() and not is_banned) or public.is_owner())
with check ((id=auth.uid() and not is_banned) or public.is_owner());

drop policy if exists profiles_delete_owner on public.profiles;
create policy profiles_delete_owner on public.profiles
for delete to authenticated
using (public.is_owner());

-- Conversations
 drop policy if exists conversations_read_participant on public.conversations;
create policy conversations_read_participant on public.conversations
for select to authenticated
using ((user_a=auth.uid() or user_b=auth.uid()) and not public.is_banned_user(auth.uid()));

drop policy if exists conversations_insert_participant on public.conversations;
create policy conversations_insert_participant on public.conversations
for insert to authenticated
with check ((user_a=auth.uid() or user_b=auth.uid()) and not public.is_banned_user(auth.uid()));

drop policy if exists conversations_delete_owner on public.conversations;
create policy conversations_delete_owner on public.conversations
for delete to authenticated
using (public.is_owner());

-- Messages
 drop policy if exists messages_read_participant on public.messages;
create policy messages_read_participant on public.messages
for select to authenticated
using (
  public.is_owner() or exists(
    select 1 from public.conversations c
    join public.profiles pa on pa.id=c.user_a
    join public.profiles pb on pb.id=c.user_b
    where c.id=conversation_id
      and (c.user_a=auth.uid() or c.user_b=auth.uid())
      and not pa.is_banned and not pb.is_banned
  )
);

drop policy if exists messages_insert_sender on public.messages;
create policy messages_insert_sender on public.messages
for insert to authenticated
with check (
  sender_id=auth.uid() and not public.is_banned_user(auth.uid()) and exists(
    select 1 from public.conversations c
    where c.id=conversation_id and (c.user_a=auth.uid() or c.user_b=auth.uid())
  )
);

drop policy if exists messages_update_sender on public.messages;
create policy messages_update_sender on public.messages
for update to authenticated
using (public.is_owner() or (sender_id=auth.uid() and not public.is_banned_user(auth.uid())))
with check (public.is_owner() or sender_id=auth.uid());

drop policy if exists messages_delete_sender on public.messages;
create policy messages_delete_sender on public.messages
for delete to authenticated
using (public.is_owner() or sender_id=auth.uid());

-- Admin RPCs for moderation that do not need the service-role key.
create or replace function public.admin_set_banned(target uuid, value boolean)
returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_owner() then raise exception 'admin only'; end if;
  if target = auth.uid() then raise exception 'owner cannot ban itself'; end if;
  update public.profiles set is_banned=value, updated_at=now() where id=target;
end; $$;

create or replace function public.admin_delete_message(target bigint)
returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_owner() then raise exception 'admin only'; end if;
  delete from public.messages where id=target;
end; $$;

create or replace function public.admin_delete_conversation(target uuid)
returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_owner() then raise exception 'admin only'; end if;
  delete from public.conversations where id=target;
end; $$;

revoke all on function public.admin_set_banned(uuid,boolean) from public;
grant execute on function public.admin_set_banned(uuid,boolean) to authenticated;
revoke all on function public.admin_delete_message(bigint) from public;
grant execute on function public.admin_delete_message(bigint) to authenticated;
revoke all on function public.admin_delete_conversation(uuid) from public;
grant execute on function public.admin_delete_conversation(uuid) to authenticated;

-- Profile creation after registration.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  base_username text;
  final_username text;
  i integer := 0;
begin
  base_username := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)), '[^a-zA-Z0-9_]', '', 'g'));
  if length(base_username) < 3 then base_username := 'user'; end if;
  final_username := left(base_username,24);
  while exists(select 1 from public.profiles where username=final_username) loop
    i := i + 1;
    final_username := left(base_username, greatest(1,24-length(i::text)-1)) || '_' || i;
  end loop;
  insert into public.profiles(id,username,display_name) values(new.id,final_username,coalesce(new.raw_user_meta_data->>'username',final_username));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();



-- Voice messages storage. The bucket is public so voice notes can play directly in GitHub Pages.
insert into storage.buckets (id, name, public) values ('voice-messages','voice-messages',true)
on conflict (id) do update set public=true;

drop policy if exists voice_upload_own on storage.objects;
create policy voice_upload_own on storage.objects for insert to authenticated
with check (bucket_id='voice-messages' and (storage.foldername(name))[1]=auth.uid()::text);

drop policy if exists voice_read_auth on storage.objects;
create policy voice_read_auth on storage.objects for select to authenticated
using (bucket_id='voice-messages');

drop policy if exists voice_delete_own on storage.objects;
create policy voice_delete_own on storage.objects for delete to authenticated
using (bucket_id='voice-messages' and (storage.foldername(name))[1]=auth.uid()::text);

-- Realtime.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.profiles;

-- ============================================================
-- ONE-TIME OWNER SETUP (run AFTER creating your own account)
-- Replace YOUR_EMAIL with the exact email of YOUR account.
-- This can only insert the owner row when it is empty.
-- ============================================================
-- insert into public.app_owner(singleton, owner_user_id)
-- select true, id from auth.users where lower(email)=lower('YOUR_EMAIL')
-- on conflict (singleton) do nothing;

-- Verify:
-- select p.email, o.owner_user_id from public.app_owner o join auth.users p on p.id=o.owner_user_id;
